package uk.ac.stir.cs.homer.homerFrameworkAPI.parameterData;

public enum Comparitor
{
	NONE, LESS_THAN, LESS_THAN_OR_EQUAL_TO, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, EQUAL, NOT_EQUAL, EQUAL_CASE_SENSITIVE, EQUAL_CASE_INSENSITIVE, NOT_EQUAL_CASE_SENSITIVE, NOT_EQUAL_CASE_INSENSITIVE;
}
